export const PARENT_ERROR_CODES = {
  PARENT_ASSIGN_INVALID_INPUT: "PARENT_ASSIGN_INVALID_INPUT",
  PARENT_ASSIGN_STUDENT_OR_PARENT_NOT_FOUND:
    "PARENT_ASSIGN_STUDENT_OR_PARENT_NOT_FOUND",
  PARENT_ASSIGN_ALREADY_LINKED: "PARENT_ASSIGN_ALREADY_LINKED",
  PARENT_UNASSIGN_INVALID_QUERY: "PARENT_UNASSIGN_INVALID_QUERY",
  PARENT_UNASSIGN_LINK_NOT_FOUND: "PARENT_UNASSIGN_LINK_NOT_FOUND",
  PARENT_STUDENT_PARENTS_INVALID_STUDENT_ID:
    "PARENT_STUDENT_PARENTS_INVALID_STUDENT_ID",
  PARENT_STUDENT_PARENTS_INVALID_QUERY:
    "PARENT_STUDENT_PARENTS_INVALID_QUERY",
  PARENT_STUDENT_PARENTS_STUDENT_NOT_FOUND:
    "PARENT_STUDENT_PARENTS_STUDENT_NOT_FOUND",
  PARENT_MY_STUDENTS_INVALID_QUERY: "PARENT_MY_STUDENTS_INVALID_QUERY",
  PARENT_MY_STUDENTS_PARENT_PROFILE_NOT_FOUND: "PARENT_PROFILE_NOT_FOUND",
  PARENT_STUDENT_SCHEDULE_INVALID_STUDENT_ID:
    "PARENT_STUDENT_SCHEDULE_INVALID_STUDENT_ID",
  PARENT_STUDENT_SCHEDULE_INVALID_QUERY:
    "PARENT_STUDENT_SCHEDULE_INVALID_QUERY",
  PARENT_STUDENT_SCHEDULE_PARENT_PROFILE_NOT_FOUND: "PARENT_PROFILE_NOT_FOUND",
  PARENT_STUDENT_SCHEDULE_STUDENT_NOT_LINKED: "STUDENT_NOT_LINKED_TO_PARENT",
  PARENT_STUDENT_ATTENDANCE_INVALID_STUDENT_ID:
    "PARENT_STUDENT_ATTENDANCE_INVALID_STUDENT_ID",
  PARENT_STUDENT_ATTENDANCE_INVALID_QUERY:
    "PARENT_STUDENT_ATTENDANCE_INVALID_QUERY",
  PARENT_STUDENT_ATTENDANCE_PARENT_PROFILE_NOT_FOUND: "PARENT_PROFILE_NOT_FOUND",
  PARENT_STUDENT_ATTENDANCE_STUDENT_NOT_LINKED: "STUDENT_NOT_LINKED_TO_PARENT",
} as const;

export type ParentErrorCode =
  (typeof PARENT_ERROR_CODES)[keyof typeof PARENT_ERROR_CODES];
